---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: retoteatro-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: retoteatro
  template:
    metadata:
      labels:
        app: retoteatro
    spec:
      containers:
      - name: retoteatro-container
        image: angeladan/retoteatro-nginx
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "80m"
          limits:
            memory: "128Mi"
            cpu: "250m"

