apiVersion: apps/v1
kind: Deployment
metadata:
  name: retoteatro-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: retoteatro
  template:
    metadata:
      labels:
        app: retoteatro
    spec:
      containers:
      - name: retoteatro-container
        image: mi-app-retoteatro:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: retoteatro-service
spec:
  selector:
    app: retoteatro
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
